- name: Install Softwares to hosts
  hosts: all
  vars:
    packages:
      - name: firewalld
        required: True
      - name: httpd
        required: True
      - name: git
        required: True
  tasks:
    - name: Install "${{item.name}}"
      dnf:
        name: "{{item.name}}"
        state: present

  when: item.required == True
  loop: "{{packages}}"
